# Dockerfile
FROM python:3.9
ADD . .
RUN pip install numpy matplotlib firebase_admin uuid flask google.cloud /deep-speaker  
#deep_speaker.audio deep_speaker.batcher deep_speaker.constants deep_speaker.conv_models deep_speaker.test 
#RUN apt-get update -y
#RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
#ENTRYPOINT ["python"]
CMD ["python", "./app.py"]