# Dockerfile
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the local directory contents into the container at /app
COPY . /app

# Install Python dependencies
RUN pip install numpy matplotlib firebase_admin uuid flask google-cloud-firestore deep-speaker multiprocessing librosa random wave 

# Install dependencies listed in requirements.txt
RUN pip install -r requirements.txt

# Command to run the Flask application
CMD ["python", "./main.py"]
